# Generated by Django 4.0.5 on 2022-07-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('season_points', models.IntegerField()),
                ('month_points', models.IntegerField()),
                ('week_points', models.IntegerField()),
            ],
        ),
    ]
